Save test execution logs in acceptance tests workflow. Closes #66

diff --git a/.github/workflows/acceptance-test.yml b/.github/workflows/acceptance-test.yml
--- a/.github/workflows/acceptance-test.yml
+++ b/.github/workflows/acceptance-test.yml
@@ -48,6 +48,43 @@ jobs:
           bats-version: 1.2.1
 
       - name: Run Test Suite
+        id: run-test-suite
+        continue-on-error: true
         run: |
           chmod +x $GITHUB_WORKSPACE/tests/acceptance/run.sh
           $GITHUB_WORKSPACE/tests/acceptance/run.sh
+          steampipe service stop --force
+
+      - name: Save Test Suite Logs
+        uses: actions/upload-artifact@v2
+        with:
+          name: test-logs
+          path: ~/.steampipe/logs
+          if-no-files-found: error
+
+      # This job checks whether the test suite has passed or not.
+      # Since the exit_code is set only when the bats test suite pass, so we have added the if-conditional block 
+      - name: Check Test Passed/Failed
+        continue-on-error: false
+        run: |
+          if [ ${{ steps.run-test-suite.outputs.exit_code }} -eq 0 ]; then
+            exit 0
+          else
+            exit 1
+          fi
+
+  clean_up:
+    # let's clean up the artifacts.
+    # incase this step isn't reached,
+    # artifacts automatically expire after 90 days anyway
+    # refer:
+    #   https://docs.github.com/en/actions/configuring-and-managing-workflows/persisting-workflow-data-using-artifacts#downloading-and-deleting-artifacts-after-a-workflow-run-is-complete
+    name: Clean Up Artifacts
+    needs: goreleaser
+    runs-on: ubuntu-latest
+    steps:
+      - name: Clean up test suite logs
+        uses: geekyeggo/delete-artifact@v1
+        with:
+          name: test-logs
+          failOnError: true
